apiVersion: v1
kind: ConfigMap # This is simply another resource, another object Kubernetes understands. As the name suggests it creates a map of configurations. So a Key Value pair list basically.
metadata:
  name: data-store-env
data:
  folder: "story"
  # Here we could have multiple key value pairs if we needed it.
