apiVersion: v1
kind: Service # Tells Kubernetes: “I want to create a Service object”
metadata:
  name: backend # Name of the Service
spec: # Service configuration
  selector:
    app: second-app # It tells the Service: “Send traffic to Pods with label app=second-app”
  ports:
    - protocol: "TCP"
      # Normal web traffic uses TCP (HTTP, HTTPS)
      port: 8000 # Clients connect to the Service using port 8000
      targetPort: 8080 # The container port
  type: LoadBalancer
  # type: ClusterIP
  # type: NodePort
