# https://www.udemy.com/course/docker-kubernetes-the-practical-guide/learn/lecture/22627673#overview

apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend

    # matchExpressions:
    #   # https://riyafa.wordpress.com/2020/06/07/kubernetes-matchexpressions-explained/
    #   - { key: app, operator: In, values: [second-app, first-app] }
    #   # Available matchExpressions Operators: In, NotIn

  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: gibsonjoseph/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            # A liveness probe tells Kubernetes how to check if your container is still “alive”.
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10 # Kubernetes checks the container every 10 seconds
            initialDelaySeconds: 5
            # Kubernetes waits 5 seconds after the container starts
            # Then it runs the first liveness check
