apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # This will do some automatic load balancing done by kubernetes but we're not getting exposed to the outside world. This will not be reachable from outside. Only from iside our cluster this service can be reached.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
