server {
  listen 80;

  location /api/ {
    # these domain name is generated automatically for the services registered in you cluster.
    # since this code now runs on the cluster, this can be evaluated and resolved by kubernetes and will actually find our taks sevice when we use this domain. And that's the cool thing about the reverse proxy, even though our code executes on inside of the browser.
    proxy_pass http://tasks-service.default:8000/;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}