apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: # “How should Kubernetes run this?”
  replicas: 2 # Two Pods are create
  selector:
    matchLabels: # Deployment says: “I manage Pods that have label app=story”. This must match Pod labels exactly.
      app: story
  template:
    metadata:
      labels:
        app: story
    spec: # Describes what runs inside the Pod.
      containers:
        - name: story
          image: gibsonjoseph/kub-data-demo:1
          volumeMounts: # Tells the container where to mount volumes.
            - mountPath: /app/story
              name: story-volume # Name of the volume to mount. Must match a volume defined below.
      volumes: # Defines volumes available to the Pod. These are Pod-level, not container-level
        # https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
        - name: story-volume # Referenced by volumeMounts
          # Type of volume: hostpath
          hostPath:
            # This allows us to set a path on the host machine, so on the node, the real machine running this pod, and then the data from that path will be exposed to the different pods. So multiple pods can now share one in the same path on the host machine instead of pod-specfic paths. And the hostPath is a bit like a bind mount.

            path: /data # Kubernetes checks if `/data` exists on the node
            type: DirectoryOrCreate # If it does not exist → it is **created automatically**
